spring:
  config:
    activate:
      on-profile: local, default
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: jang
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    database: h2
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 411248812193-4l1bma5db82rdig55dg12u9cs2f5vbqk.apps.googleusercontent.com
#            client-secret: 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
#            scope: email,profile
  mvc:
    hiddenmethod:
      filter:
        enabled=true:logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

---
spring:
  config:
    activate:
      on-profile: test


